apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quality-air-hpa
  namespace: quality-air
  labels:
    app: quality-air-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quality-air-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      # Default is 300s (5 minutes). We lower to 30s so pods downscale rapidly when traffic stops!
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max
