apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quality-air

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

images:
  - name: europe-west1-docker.pkg.dev/myproject-329912/quality-air-repo/quality-air-app
    newTag: latest

