apiVersion: v1
kind: Service
metadata:
  name: quality-air-service
  namespace: quality-air
  labels:
    app: quality-air-app
spec:
  type: LoadBalancer
  selector:
    app: quality-air-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http

